### ISSUE TITLE
Are there any tests for this?

### ISSUE THREAD

**Issue by NorthIsUp** [rewardz/django_model_helpers#2]
This looks awesome but it is hard to trust given there are no tests. I may be able to get to add some for the specific helpers we want to use. But that will be in several weeks.

**Comment by ramast** [comment]
I know test cases are needed, I will work on it then email you again.
Just wanted to be sure you have interest in merging the repo.

Cheers,
Ramast

**Comment by ramast** [comment]
Sorry for sounding like a weirdo with all talking about merge. I mixed up :)
I am writing test cases for the module but I can assure you this code is already well tested as part of the project that uses it.

**Comment by ramast** [comment]
Tests has been provided with 100% code coverage
