### ISSUE TITLE
Exception in get_value

### ISSUE THREAD

**Issue by shashisp** [rewardz/django_model_helpers#4]
`get_value` breaks if there's no choice
 `choice_name, choice = self._choices_id[choice_id]`
`KeyError: None`

**Comment by ramast** [comment]
Try `get_value("some_val", raise_exception=False)`

**Comment by shashisp** [comment]
and if there's no choice for `get_code_name`,  add `raise_exception` argument may be?

**Comment by ramast** [comment]
get_code_name take the id stored in DB and return corresponding codename.
What is a valid scenario where the ID doesn't exist and you don't want that to be exception?

I would add the argument of there is a good reason.

Otherwise u can always handle the exception

```
try:
    ...get_code_name
except KeyError:
    # do something
```
